version: "3.8"

services:
  mongodb:
    image: mongo
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
    container_name: app
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    command: mix phx.server

volumes:
  mongodb_data:
